
CREATE TABLE FP_Customer
(
CustomerID NUMERIC(5,0) NOT NULL,
CustomerName VARCHAR(50) NOT NULL,
PhoneNumber NUMERIC(9,0) NOT NULL,
Email VARCHAR(50),
ADDRESS VARCHAR(70),
	CONSTRAINT FP_Customer_PK PRIMARY KEY(CustomerID)
);

CREATE TABLE FP_MiscItem
(
ItemID NUMERIC(5,0) NOT NULL,
ItemName VARCHAR(50) NOT NULL,
AmountInstock NUMERIC(3,0) NOT NULL,
Condition VARCHAR(50) NOT NULL,
	CONSTRAINT FP_MISCITEM_PK PRIMARY KEY(ItemID)
);

CREATE TABLE FP_Service
(
ServiceID NUMERIC(5,0) NOT NULL,
SERVICENAME VARCHAR(50) NOT NULL,
PRICE NUMERIC(7,2),
TIMEINMINUTE NUMERIC(3,0),
DESCRIPTION VARCHAR(100),
	CONSTRAINT FP_SERVICE_PK PRIMARY KEY(ServiceID)
);

CREATE TABLE FP_Staff
(
StaffID NUMERIC(5,0) NOT NULL,
StaffNAME VARCHAR(50) NOT NULL,
phoneNumber NUMERIC(9,0),
Email VARCHAR(50),
	CONSTRAINT FP_Staff_PK PRIMARY KEY(StaffID)
);

CREATE TABLE FP_VehiclePart
(
ItemID NUMERIC(5,0) NOT NULL,
ITEMNAME VARCHAR(50) NOT NULL,
AMOUNTINSTOCK NUMERIC(3,0),
CONDITION VARCHAR(50),
ARRIVALDATE VARCHAR(50),
MAKEMODELYEAR VARCHAR(50),
	CONSTRAINT FP_VEHICLEPART_PK PRIMARY KEY(ITEMID)
);

CREATE TABLE FP_WorkTicket
(
WorkTicketID NUMERIC(5,0) NOT NULL,
staffID NUMERIC(5,0),
CustomerID NUMERIC(5,0) NOT NULL,
ServiceID NUMERIC(5,0) NOT NULL,
SERVICEDATE VARCHAR(50),
	CONSTRAINT FP_WORKTICKET_PK PRIMARY KEY(WorkTicketID),
	CONSTRAINT FP_WORKTICKET_FP_STAFF_FK FOREIGN KEY(staffID) REFERENCES FP_STAFF(staffID),
	CONSTRAINT FP_WORKTICKET_FP_CUSTOMER_FK FOREIGN KEY(CustomerID) REFERENCES FP_CUSTOMER(CustomerID),
	CONSTRAINT FP_WORKTICKET_FP_SERVICE_FK FOREIGN KEY(ServiceID) REFERENCES FP_SERVICE(ServiceID)
);